---
- hosts: kubernetes-master-nodes  

  tasks:
  - name: Copy storageclass & PVC & Pod YAML Files 
    template: src=storageclass_ontap.yaml basic-pvc.yaml task-pv-pod.yaml dest=/home/sangwon
    
  - name: Creating basic storageclass 
    shell: kubectl create -f storageclass_ontap.yaml
    args:
      chdir: /home/sangwon
