---
- hosts: kubernetes-master-nodes  

  tasks:
  - name: Copy storageclass YAML File
    template: src=storageclass_ontap.yaml dest=/home/sangwon
    
  - name: Creating basic storageclass 
    shell: kubectl create -f storageclass_ontap.yaml
    args:
      chdir: /home/sangwon

- name: Copying PVC  YAML File
    template: src=basic-pvc.yaml dest=/home/sangwon
    
  - name: Creating basic pvc
    shell: kubectl create -f basic-pvc.yaml
    args:
      chdir: /home/sangwon
